resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/d8091767addc1a51e11cb2f04392e4eb40e39b18/snapshot.yaml

packages:
  - .
  - test
  - crypto
  - crypto/test
  - validate-mainnet

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: d8091767addc1a51e11cb2f04392e4eb40e39b18
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 5bca69f048c4d599c362d797ee8b036c118f77f4
    subdirs:
      - binary
      - binary/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 30f2728662e782c50f2da1f66f4b3159e85c8ff1
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  - sequence-0.9.8
  - tasty-hedgehog-0.2.0.0
  # To be able to use `stack hoogle`
  - haskell-src-exts-1.21.0

  # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: df73a199d49ff9a5e958c65414e74fdeece15897

  - time-units-1.0.0@sha256:27cf54091c4a0ca73d504fc11d5c31ab4041d17404fe3499945e2055697746c1
  - ekg-0.4.0.15@sha256:f52d7c00654d72d2ab988255f30adba95a52484ac310bab9c136c64732e69f4b
  - ekg-json-0.1.0.6@sha256:4ff2e9cac213a5868ae8b4a7c72a16a9a76fac14d944ae819b3d838a9725569b

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 00413dcad916a41cf392437199cfba7a2e2c76d7
    subdirs:
      - contra-tracer
      - iohk-monitoring

  # Needed for IOHK monitoring
  - libyaml-0.1.0.0

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: e8bfc1294e088f90e5ae0b4aedbc82ee46ac5ee4
    subdirs:
      - .

nix:
  shell-file: scripts/nix/stack-shell.nix
